#!/bin/sh

# https://stackoverflow.com/questions/40462111/git-prevent-commits-in-master-branch

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi